version: '3.9'

services:
  db:
    image: docker.arvancloud.ir/mariadb
    container_name: wp_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: DB_ROOT_PASSWORD
      MYSQL_DATABASE: DB_NAME
      MYSQL_USER: DB_USER
      MYSQL_PASSWORD: DB_PASSWORD
      MYSQL_INITDB_SKIP_TZINFO: 1
    volumes:
      - db_data:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - wp_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    image: docker.arvancloud.ir/wordpress
    container_name: wp_app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: DB_USER
      WORDPRESS_DB_PASSWORD: DB_PASSWORD
      WORDPRESS_DB_NAME: DB_NAME
      WORDPRESS_TABLE_PREFIX: WP_PREFIX
      WORDPRESS_DEBUG: WP_DEBUG
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_MEMORY_LIMIT', '256M');
        define('WP_AUTO_UPDATE_CORE', false);
    volumes:
      - wp_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "8080:80"
    networks:
      - wp_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/wp-includes/version.php || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ./db_data
      o: bind
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: ./wp_data
      o: bind

networks:
  wp_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24